# Generated by Django 4.2.7 on 2023-11-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpages',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='pages.imagegroups', verbose_name='Изображения'),
        ),
    ]
